version: '3.1'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
          
  schemaregistry:
    platform: linux/amd64
    image: confluentinc/cp-schema-registry:5.1.2
    container_name: schemaregistry
    hostname: schemaregistry
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_HEAP_OPTS: -Xms1g -Xmx1g
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8085:8085        

  schemaregistry-ui:
    platform: linux/amd64
    image: landoop/schema-registry-ui
    container_name: schemaregistryui
    hostname: schemaregistryui
    restart: always
    depends_on:
      - schemaregistry
    environment:
      SCHEMAREGISTRY_URL: "http://192.168.1.52:8085"
      PROXY : "true"
    ports:
      - 8000:8000

  rest-proxy:
    image: confluentinc/cp-kafka-rest
    ports:
    - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082/"
      KAFKA_REST_HOST_NAME: "rest-proxy"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://192.168.1.52:8085"
    depends_on:
    - "kafka"
    - "schemaregistry"      

  topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    ports:
    - "8086:8086"
    environment:
      PORT: "8086"
      PROXY: "true"
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
    depends_on:
    - "rest-proxy"